### PR TITLE
Feature: allow specifying the endpoint type and tls options

### PR DESCRIPTION
**Pull request by rwos**
1 = normal docker
2 = portainer agent
3 = azure

see https://app.swaggerhub.com/apis/deviantony/Portainer/1.20.0/#/endpoints/EndpointCreate

### CODE REVIEW

**Comment by rwos** [comment]
* [x] fix new linting errors

**Review by rwos — COMMENTED** [review]
@till so the code works, but I'm still trying to figure out what's up with the test...

**Comment by till** [comment]
@rwos That looks like maybe `docker` or `docker-py` were upgraded?

**Comment by till** [comment]
Maybe we should `pip install docker-py==1.10.6`? That seems to be working in previous builds:
https://app.circleci.com/jobs/github/pngmbh/ansible-role-portainer/23

**Comment by rwos** [comment]
@till I pinned the molecule image now - that also seems to work 🤷‍♂

**Pull request merged**
